name: Release
on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: Version tag
        default: '1.0.0'
        required: true
      unit_tests:
        description: Run unit tests
        type: boolean
        required: true
        default: false

jobs:
  build-artifacts:
    permissions:
      contents: write

    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm-based Macs (M1 and above).
            args: '--target aarch64-apple-darwin'
            yaak_arch: 'arm64'
            os: 'macos'
            name: 'Mac OS ARM64'
            targets: 'aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel-based Macs.
            args: '--target x86_64-apple-darwin'
            yaak_arch: 'x64'
            os: 'macos'
            name: 'Mac OS x64'
            targets: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            yaak_arch: 'x64'
            os: 'ubuntu'
            name: 'Linux x64'
            targets: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
            yaak_arch: 'arm64'
            os: 'ubuntu'
            name: 'Linux ARM64'
            targets: ''
          - platform: 'windows-latest'
            args: ''
            yaak_arch: 'x64'
            os: 'windows'
            name: 'Windows x64'
            targets: ''
          # Windows ARM64
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'
            yaak_arch: 'arm64'
            os: 'windows'
            name: 'Windows ARM64'
            targets: 'aarch64-pc-windows-msvc'
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}

      - name: Install dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev xdg-utils

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install JS modules
        run: npm ci
      - name: Run JS Tests
        run: npm test
        if: ${{ github.event.inputs.unit_tests == 'true' }}
      - name: Run Rust Tests
        run: cargo test --all
        if: ${{ github.event.inputs.unit_tests == 'true' }}
        working-directory: src-tauri

      - name: Set version
        run: npm run replace-version
        env:
          YAAK_VERSION: ${{ github.event.inputs.version_tag }}

      - name: Build release
        uses: RubisetCie/tauri-action@dev
        env:
          YAAK_TARGET_ARCH: ${{ matrix.yaak_arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'v__VERSION__'
          releaseName: 'Release __VERSION__'
          releaseBody: 'Stable release of **Yeek** aligned with **Yaak** __VERSION__'
          releaseDraft: true
          prerelease: false
          args: '${{ matrix.args }} --config ./src-tauri/tauri.release.conf.json'
